### ISSUE TITLE
`make dev-deps` failing to install goreleaser

### ISSUE THREAD

**Issue by powersjcb** [blend/go-sdk#198]
**What happened**:
`make dev-deps` fails to install goreleaser
```
$ go get github.com/goreleaser/goreleaser
package github.com/google/go-github/v28/github: cannot find package "github.com/google/go-github/v28/github" in any of:
	/usr/local/Cellar/go/1.14.3/libexec/src/github.com/google/go-github/v28/github (from $GOROOT)
	/Users/jpowers/go/src/github.com/google/go-github/v28/github (from $GOPATH)
```

**Resolution**:
Install goreleaser with go modules enabled
```
$ GO111MODULE=on go get -d github.com/goreleaser/goreleaser
go: github.com/goreleaser/goreleaser upgrade => v0.138.0
```
Reference: https://github.com/goreleaser/goreleaser/issues/1013

**Environment**:
- fresh laptop, go installed using homebrew
- go-sdk version: master 
- go version (e.g `go version`): go version go1.14.3 darwin/amd64
- OS (e.g: `cat /etc/os-release`): darwin

**Comment by dhermes** [comment]
That is quite surprising since `gomod` has been on by default since like 1.12 or 1.13.

**Comment by powersjcb** [comment]
Hmm, if you clone this project into `$GOPATH/src/`, then the config for `GO111MODULE=off` will be used as a default since there is no project level go.mod file.

https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k

**Comment by dhermes** [comment]
Yeah I just reproduced on my dev machine, I just was surprised by the behavior and yet to see it in the wild. I ran the `go get` command fully outside of `$GOPATH` (with `go1.14`) and saw the same behavior.

**Comment by powersjcb** [comment]
Yeah, upon reading the documentation for goreleaser, they recommend installing a pinned binary release directly.

(In general, I've seen problems with using `go get` to install dev dependencies because it doesn't pin the versions. However, this does work nicely as a cross platform way to install the dep.)
